[project]
name = "take-five"
version = "0.1.0"
description = "Django improvisation"
dependencies = [
    "django~=4.2.15",
    "django-extensions==3.2.3",
    "django-debug-toolbar>=4.4.6",
    "django-unfold>=0.36.0",
    "django-select2>=8.2.1",
    "django-selectize>=2.0",
]
requires-python = ">=3.10"
readme = "README.md"
license = {text = "MIT"}


[tool.pdm]
distribution = false

[tool.pdm.dev-dependencies]
dev = [
    "ipython>=8.26.0",
]
