# Generated by Django 4.2.14 on 2024-08-11 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kiwi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeywordParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kiwi.keyword')),
            ],
        ),
    ]
