# Generated by Django 4.2.13 on 2024-05-29 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0002_alter_keywordarg_options_alter_keywordarg_keyword'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='doc',
            field=models.TextField(default='', verbose_name='Documentation'),
            preserve_default=False,
        ),
    ]
