# Generated by Django 4.2.13 on 2024-05-29 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0004_keywordarg_unique_kw_arg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='doc',
            field=models.TextField(blank=True, verbose_name='Documentation'),
        ),
    ]
