# Generated by Django 4.2.13 on 2024-05-29 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0005_alter_keyword_doc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keywordarg',
            name='default_value',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
