# Generated by Django 4.2.13 on 2024-05-29 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0006_alter_keywordarg_default_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keywordarg',
            name='default_value',
            field=models.CharField(max_length=255),
        ),
    ]
