# Generated by Django 4.2.14 on 2024-07-23 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('i18n_bug', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='title',
            field=models.CharField(choices=[('Dr.', 'Dr.'), ('Rep.', 'Rep.')], max_length=10),
        ),
    ]
