# Generated by Django 4.2.13 on 2024-05-29 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='keywordarg',
            options={'verbose_name': 'Parameter'},
        ),
        migrations.AlterField(
            model_name='keywordarg',
            name='keyword',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='args', to='keywords.keyword'),
        ),
    ]
